NAME = ft_display_file
SRC = ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -c -Wall -Werror -Wextra $(SRC)
	gcc -o $(NAME) ft_display_file.o

clean:
	$(RM) ft_display_file.o

fclean: clean
	$(RM) $(NAME)
